# Generated by Django 5.0.2 on 2024-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='create_acnt',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
